# Generated by Django 5.2.7 on 2025-10-01 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Ingrediente')),
                ('quantidade', models.FloatField(default=0.0, verbose_name='Quantidade em Stock')),
                ('unidade', models.CharField(default='unidade', max_length=20, verbose_name='Unidade (ex: kg, l, unidade)')),
                ('preco_por_unidade', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço por Unidade')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Título do Prato')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço de Venda')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento_compra', models.DateTimeField(auto_now_add=True)),
                ('item_cardapio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.itemcardapio')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitoReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=0.0)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.ingrediente')),
                ('item_cardapio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='estoque.itemcardapio')),
            ],
        ),
    ]
